=== oycii/Content/doc/data/playfon/exportXML.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % boolean "(1|0)">
<!ENTITY % url "CDATA">
<!ENTITY % fieldlist "CDATA">
<!ELEMENT catalog (service_groups, phones?, media_formats, format_instances, platforms?, genres?, deleted_items?, items)>
<!ATTLIST catalog
	update_id NMTOKEN #REQUIRED
	update_to NMTOKEN #REQUIRED
	media_type CDATA #REQUIRED
	region CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ELEMENT genres (genre+)>
<!ELEMENT genre EMPTY>
<!ATTLIST genre
	id NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	isadult %boolean; #IMPLIED
>
<!ELEMENT item (description?, screenshots?, previews?)>
<!ATTLIST item
	id NMTOKEN #REQUIRED
	name CDATA #IMPLIED
	short_name CDATA #IMPLIED
	genre_id NMTOKEN #REQUIRED
	singer CDATA #IMPLIED
	supported_phones %fieldlist; #IMPLIED
	fi_ids %fieldlist; #REQUIRED
	ispremium %boolean; #IMPLIED
	isrus %boolean; #IMPLIED
	platform_id NMTOKEN #IMPLIED
>
<!ELEMENT items (item*)>
<!ATTLIST items
	platform_default NMTOKEN #IMPLIED
>

<!ELEMENT deleted_item EMPTY>
<!ATTLIST deleted_item
	id NMTOKEN #REQUIRED
>
<!ELEMENT deleted_items (deleted_item+)>
<!ELEMENT media_format EMPTY>
<!ATTLIST media_format
	id NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	code_mask CDATA #REQUIRED
	code_mask_old CDATA #REQUIRED
	preview_field CDATA #IMPLIED
	supported_phones %fieldlist; #IMPLIED
>
<!ELEMENT media_formats (media_format+)>
<!ELEMENT format_instance EMPTY>
<!ATTLIST format_instance
	id NMTOKEN #REQUIRED
	mf_id NMTOKEN #REQUIRED
	sg_id NMTOKEN #REQUIRED
>
<!ELEMENT format_instances (format_instance+)>
<!ELEMENT service EMPTY>
<!ATTLIST service
	id NMTOKEN #REQUIRED
	operator_name CDATA #REQUIRED
	phone CDATA #REQUIRED
	real_price CDATA #REQUIRED
	operator_logo %url; #IMPLIED
>
<!ELEMENT phone EMPTY>
<!ATTLIST phone
	id NMTOKEN #REQUIRED
	vendor CDATA #IMPLIED
	model CDATA #REQUIRED
	supported_media_formats %fieldlist; #IMPLIED
>
<!ELEMENT phones (phone+)>
<!ELEMENT service_group (service+)>
<!ATTLIST service_group
	id NMTOKEN #REQUIRED
	price CDATA #REQUIRED
>
<!ELEMENT service_groups (service_group+)>
<!ELEMENT platform EMPTY>
<!ATTLIST platform
	id NMTOKEN #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT platforms (platform+)>
<!ELEMENT screenshot EMPTY>
<!ATTLIST screenshot
	url %url; #REQUIRED
	default %boolean; #IMPLIED
	small %boolean; #IMPLIED
>
<!ELEMENT screenshots (screenshot+)>
<!ELEMENT preview EMPTY>
<!ATTLIST preview
	name CDATA #REQUIRED
	url %url; #REQUIRED
>
<!ELEMENT previews (preview+)>

=== oycii/Content/doc/data/playfon/videotone.xml
<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE catalog SYSTEM "http://wwwg.playfon.ru/exportXML.dtd">
<catalog update_id="0" update_to="" media_type="videotone" region="RU"><service_groups><service_group id="300" price="3.00"><service id="804" operator_name="Билайн" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/beeline.gif"/><service id="24" operator_name="МТС" phone="1717" real_price=" 135,12  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/mts.gif"/><service id="25" operator_name="Мегафон Москва" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/megafon.gif"/><service id="26" operator_name="Мегафон Поволжье" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/megafon.gif"/><service id="27" operator_name="Мегафон Кавказ" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/megafon.gif"/><service id="33" operator_name="СМАРТС" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/smarts.gif"/><service id="34" operator_name="Байкалвестком" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/bwc.gif"/><service id="415" operator_name="Мегафон-Сибирь" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/megafon.gif"/><service id="604" operator_name="Теле2" phone="1717" real_price=" 129,80  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/tele2.gif"/><service id="96" operator_name="НТК" phone="1717" real_price=" 136,88  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/ntk.gif"/><service id="128" operator_name="Пенза GSM" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/smarts.gif"/><service id="364" operator_name="Stek-GSM" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/stek.gif"/><service id="481" operator_name="Мотив" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/motiv.gif"/><service id="256" operator_name="Мегафон Дальний Восток" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/megafon.gif"/><service id="225" operator_name="Мегафон центр" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/megafon.gif"/><service id="245" operator_name="Шупашкар-GSM" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/smarts.gif"/><service id="292" operator_name="Мегафон Северо-Запад" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/megafon.gif"/><service id="267" operator_name="Енисей Телеком" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/enisei.gif"/><service id="304" operator_name="Мегафон-Урал" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/megafon.gif"/><service id="316" operator_name="Ютел" phone="1717" real_price=" 123,90  рубля с НДС" operator_logo="http://img.playfon.ru/img/operators/usi.gif"/><service id="375" operator_name="Элайн" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/elane.gif"/><service id="405" operator_name="СМАРТС (Иваново)" phone="1717" real_price=" 125  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/smarts.gif"/><service id="447" operator_name="Астрахань GSM" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/smarts.gif"/><service id="501" operator_name="Оренбург-GSM" phone="1717" real_price=" 105,85  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/orenburg.gif"/><service id="512" operator_name="НСС Ульяновск" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/smarts.gif"/><service id="557" operator_name="НСС Чувашия" phone="1717" real_price=" 132,73  рубля с НДС" operator_logo="http://img.playfon.ru/img/operators/tele2.gif"/><service id="546" operator_name="НСС Саратов" phone="1717" real_price=" 132,73  рубля с НДС" operator_logo="http://img.playfon.ru/img/operators/tele2.gif"/><service id="701" operator_name="СМАРТС (Ярославль)" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/smarts.gif"/><service id="828" operator_name="СМАРТС (Волгоград)" phone="1717" real_price=" 130  рублей с НДС" operator_logo="http://img.playfon.ru/img/operators/smarts.gif"/><service id="584" operator_name="НСС Нижний Новгород" phone="1717" real_price=" 132,73  рубля с НДС" operator_logo="http://img.playfon.ru/img/operators/ncc.jpg"/><service id="590" operator_name="Улан-Удэнская Сотовая сеть" phone="1717" real_price=" 130  рублей с НДС" operator_logo=""/><service id="567" operator_name="НСС Татарстан" phone="1717" real_price=" 132,73  рубля с НДС" operator_logo=""/><service id="759" operator_name="НСС Мордовия" phone="1717" real_price=" 132,79  рубля с НДС" operator_logo=""/></service_group></service_groups><phones/><media_formats><media_format id="2" name="Видеозвонки" code_mask="xxxxvt49" code_mask_old="02xxxx49"/></media_formats><format_instances><format_instance id="302" mf_id="2" sg_id="300"/></format_instances><items/></catalog>
